<?php

/**
 * Implementation of hook_install().
 */
function ca_lessons_install() {
  variable_set('ca_lessons_list_template', 'ca_lessons_list_template_one');
  variable_set('ca_lessons_node_template', 'ca_lessons_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_lessons_uninstall() {
  variable_del('ca_lessons_list_template');
  variable_del('ca_lessons_node_template');
}
