<?php

include_once('ca_lessons.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_lessons_perm() {
  return array('ca_lessons change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_lessons_menu() {
  $items['admin/settings/ca_lessons'] = array(
    'title' => 'CA Lessons: Admin',
    'description' => 'Change the look and feel of the ca_lessons module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_lessons_admin_settings_form'),
    'access arguments' => array('ca_lessons change templates'),
    'file' => 'ca_lessons.admin.inc',
    'file path' => drupal_get_path('module', 'ca_lessons') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_lessons_action_info() {
  return array(
    'ca_lessons_add_lessons_admin_action' => array(
      'type' => 'user',
      'description' => t('Add lesson administrator role'),
    ),
    'ca_lessons_remove_lessons_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove lesson administrator role'),
    ),
    'ca_lessons_add_lessons_writer_action' => array(
      'type' => 'user',
      'description' => t('Add lesson writer role'),
    ),
    'ca_lessons_remove_lessons_writer_action' => array(
      'type' => 'user',
      'description' => t('Remove lesson writer role'),
    ),
  );
}

function ca_lessons_add_lessons_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'lesson administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_lessons_add_lessons_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Lesson Administrator',
  );
  return $form;
}

function ca_lessons_add_lessons_admin_action_submit(&$form, &$form_state) {
  
}

function ca_lessons_remove_lessons_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'lesson administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_lessons_remove_lessons_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Lesson Administrator',
  );
  return $form;
}

function ca_lessons_remove_lessons_admin_action_submit(&$form, &$form_state) {
  
}

function ca_lessons_add_lessons_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'lesson writer') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_lessons_add_lessons_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Lesson Writer',
  );
  return $form;
}

function ca_lessons_add_lessons_writer_action_submit(&$form, &$form_state) {
  
}

function ca_lessons_remove_lessons_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'lesson writer') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_lessons_remove_lessons_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Lesson Writer',
  );
  return $form;
}

function ca_lessons_remove_lessons_writer_action_submit(&$form, &$form_state) {
  
}  

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_lessons_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_lessons_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_lessons' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_lessons') . "/css/ca_lessons.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_lessons_views_pre_render(&$view) {
  if ($view->name == 'lessons') {
    drupal_add_css(drupal_get_path('module', 'ca_lessons') . "/css/ca_lessons.css", 'module', 'all', FALSE);
  }
}
